#!/bin/bash

usage() { echo "Usage: $0 [-rows|-cols] [file_path]" 1>&2; exit 1; }
stat_rows() {
    if [ -f $1 ] ;then
        #cat $1 | tr ' ' '\t'
        ln=`wc -l < $1`;
    else
        #echo $1 | tr ' ' '\t'
        ln=`echo $1 | wc -l`
    fi
    i=1
    while read line 
    do
        sum=0
        n=${#arr[@]}
        ni=$(($n/2))
        arr=($line);
        for j in ${arr[@]}; do let sum+=$j; done
        avg=$((($sum+$ni)/${#arr[@]}));
        IFS=$'\n'; 
        sorted=($(sort -n <<< "${arr[*]}"));
        unset IFS;
        #echo "${sorted[@]}"
        mean=${sorted[$ni]}
        averages+=($avg)
        medians+=($mean)
        i=$(($i+1))
    done < $1
    print_table averages[@] medians[@] 0
}
stat_cols() {
    #cat $1 | tr ' ' '\t'
    ln=`wc -l < $1`
    cn=`awk '{print NF}' $1 | sort -nu | tail -1`
    i=1
    while test $i -le $cn
    do
        sum=0
        lnm=$(($ln/2))
        arr=`cut -d' ' -f$i $1`
        for j in ${arr[@]}; do let sum+=$j; done
        avg=$((($sum+$lnm)/$ln));
        IFS=$'\n'; 
        sorted=($(sort -n <<< "${arr[*]}"));
        unset IFS;
        #echo "${sorted[@]}"
        mean=${sorted[$lnm]}
        averages+=($avg)
        medians+=($mean)
        i=$(($i+1))
    done < $1
    print_table averages[@] medians[@] 1
}
print_table() {
    declare -a avg=("${!1}")
    declare -a mean=("${!2}")
    if [ $3 -eq 1 ] ;then #col
        echo "Averages:"
        for i in ${avg[@]}
        do
            printf '%.*f\t' 0 $i
        done
        echo -e "\nMedians:"
        for i in ${mean[@]}
        do
            printf '%.*f\t' 0 $i
        done
        echo
    else #row
        echo -e "Average\tMedian"
        for i in "${!avg[@]}"
        do
            printf '%.*f\t' 0 ${avg[$i]}
            printf '%.*f\n' 0 ${mean[$i]}
        done
    fi
}

while [ $# -gt 0 ]
do
    case $1 in
        -r*)
            if [[ -f $2 ]] ; then 
                stat_rows $2
            else
                cat > tmp
                stat_rows tmp
                rm -f tmp
            fi
            ;;
        -c*)
            if [[ -f $2 ]] ; then 
                stat_cols $2
            else
                cat > tmp
                stat_cols tmp
                rm -f tmp
            fi
            ;;
        -*)
            usage
            ;;
        *)
            break
            ;;
    esac
    shift
done
exit 0
